// Generate src/data/csv-data.ts from the canonical docs/*.csv exports.
//
// The CSVs are the source of truth, but a raw `?raw` import only works under
// Vite (dev/build/test). The Node CLIs (tsx) can't load .csv directly, so we
// embed the CSV text into a plain .ts module that BOTH toolchains import.
//
// Re-run via `npm run embed` (also runs automatically before dev/build/test/batch).

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const docs = join(root, "docs");

function read(name: string): string {
  return readFileSync(join(docs, name), "utf8");
}

const out = `// AUTO-GENERATED by scripts/embed-csv.ts — do NOT edit by hand.
// Source of truth: docs/Sigil *.csv (the Box exports). Run \`npm run embed\` to regenerate.

export const charactersCsv = ${JSON.stringify(read("Sigil Characters.csv"))};
export const eventsCsv = ${JSON.stringify(read("Sigil Events.csv"))};
export const itemsCsv = ${JSON.stringify(read("Sigil Items.csv"))};
`;

writeFileSync(join(root, "src", "data", "csv-data.ts"), out);
console.log("Wrote src/data/csv-data.ts from docs/*.csv");
